global:
  scrape_interval: 5s
  evaluation_interval: 7s

scrape_configs:
  - job_name: 'pavement-classifier'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: '/metrics'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']